# Generated by Django 2.1.5 on 2021-12-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('quiz_no', models.IntegerField()),
                ('rating_ps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingTotal',
            fields=[
                ('quiz_no', models.IntegerField(primary_key=True, serialize=False)),
                ('rating_sum', models.IntegerField()),
                ('rating_avg', models.IntegerField()),
                ('rating_cnt', models.IntegerField()),
            ],
        ),
    ]
