# Generated by Django 2.1.5 on 2021-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_no', models.IntegerField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(max_length=30)),
                ('quiz_content', models.CharField(max_length=1000)),
                ('hint1', models.CharField(max_length=1000)),
                ('hint1_response', models.CharField(max_length=100)),
                ('hint2', models.CharField(max_length=1000)),
                ('hint2_response', models.CharField(max_length=100)),
                ('hint3', models.CharField(max_length=1000)),
                ('hint3_response', models.CharField(max_length=100)),
                ('hint4', models.CharField(max_length=1000)),
                ('hint4_response', models.CharField(max_length=100)),
                ('hint5', models.CharField(max_length=1000)),
                ('hint5_response', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=1000)),
                ('answer_keyword', models.CharField(max_length=200)),
                ('quiz_summary', models.CharField(max_length=500)),
                ('quiz_image', models.CharField(max_length=200)),
            ],
        ),
    ]
