# Generated by Django 2.1.5 on 2021-12-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_solvedquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
